import './globals.css';

import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { ThemeProvider } from './components/theme-provider';
import { cookieToInitialState } from 'wagmi';
import { Analytics } from '@vercel/analytics/react';
import { config } from '../../config';
import Web3ModalProvider from '../../context';
import { Inter as FontSans } from 'next/font/google';

import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'));
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen font-sans antialiased bg-gray-900',
          fontSans.variable
        )}
      >
        <Toaster />

        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
        >
          <Web3ModalProvider initialState={initialState}>
            {children}
            <Analytics />
          </Web3ModalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
